// DO NOT EDIT!
// This file is generated by the api generator.

// +build !feature

package harvest

import (
	"net/url"
)

type ClientService struct {
	endpoint CrudTogglerEndpoint
}

func NewClientService(endpoint CrudTogglerEndpoint) *ClientService {
	service := ClientService{
		endpoint: endpoint,
	}
	return &service
}

func (s *ClientService) All(clients *[]*Client, params url.Values) error {
	return s.endpoint.All(clients, params)
}

func (s *ClientService) Find(id int, client *Client, params url.Values) error {
	return s.endpoint.Find(id, client, params)
}

func (s *ClientService) Create(client *Client) error {
	return s.endpoint.Create(client)
}

func (s *ClientService) Update(client *Client) error {
	return s.endpoint.Update(client)
}

func (s *ClientService) Delete(client *Client) error {
	return s.endpoint.Delete(client)
}

func (s *ClientService) Toggle(client *Client) error {
	return s.endpoint.Toggle(client)
}
