// DO NOT EDIT!
// This file is generated by the api generator.

// +build !feature

package harvest

import (
	"net/url"
)

type TaskService struct {
	endpoint	CrudEndpoint
	processor	RequestProcessor
}

func NewTaskService(endpoint CrudEndpoint, processor RequestProcessor) *TaskService {
	service := TaskService{
		endpoint:	endpoint,
		processor:	processor,
	}
	return &service
}

func (s *TaskService) All(tasks *[]*Task, params url.Values) error {
	return s.endpoint.All(tasks, params)
}

func (s *TaskService) Find(id int, task *Task, params url.Values) error {
	return s.endpoint.Find(id, task, params)
}

func (s *TaskService) Create(task *Task) error {
	return s.endpoint.Create(task)
}

func (s *TaskService) Update(task *Task) error {
	return s.endpoint.Update(task)
}

func (s *TaskService) Delete(task *Task) error {
	return s.endpoint.Delete(task)
}
