// DO NOT EDIT!
// This file is generated by the api generator.

// +build !feature

package harvest

import (
	"net/url"
	"reflect"
	"testing"
)

var (
	expectedTaskServiceParams	= url.Values{"foo": []string{"bar"}}

	testsTaskService	= map[string]struct {	// apiFn to testData
		testData	*apiWrapperTestData
		testFn		testFunc
		args		[]interface{}
	}{
		"All": {
			&apiWrapperTestData{
				expectedParams:		expectedTaskServiceParams,
				expectedDataType:	reflect.TypeOf(&[]*Task{}),
				expectedErrorMessage:	"ERR",
			},
			testApiAllWrapper,
			[]interface{}{&[]*Task{}, expectedTaskServiceParams},
		},
		"Find": {
			&apiWrapperTestData{
				expectedParams:		expectedTaskServiceParams,
				expectedIdType:		reflect.TypeOf(12),
				expectedDataType:	reflect.TypeOf(&Task{}),
				expectedErrorMessage:	"ERR",
			},
			testApiFindWrapper,
			[]interface{}{12, &Task{}, expectedTaskServiceParams},
		},
		"Create": {
			&apiWrapperTestData{
				expectedDataType:	reflect.TypeOf(&Task{}),
				expectedErrorMessage:	"ERR",
			},
			testApiCreateWrapper,
			[]interface{}{&Task{}},
		},
		"Update": {
			&apiWrapperTestData{
				expectedDataType:	reflect.TypeOf(&Task{}),
				expectedErrorMessage:	"ERR",
			},
			testApiUpdateWrapper,
			[]interface{}{&Task{}},
		},
		"Delete": {
			&apiWrapperTestData{
				expectedDataType:	reflect.TypeOf(&Task{}),
				expectedErrorMessage:	"ERR",
			},
			testApiDeleteWrapper,
			[]interface{}{&Task{}},
		},
	}
)

func TestTaskServiceAll(t *testing.T) {
	testTaskServiceMethod(t, "All")
}

func TestTaskServiceFind(t *testing.T) {
	testTaskServiceMethod(t, "Find")
}

func TestTaskServiceCreate(t *testing.T) {
	testTaskServiceMethod(t, "Create")
}

func TestTaskServiceUpdate(t *testing.T) {
	testTaskServiceMethod(t, "Update")
}

func TestTaskServiceDelete(t *testing.T) {
	testTaskServiceMethod(t, "Delete")
}

func testTaskServiceMethod(t *testing.T, name string) {
	called := false
	test, ok := testsTaskService[name]
	if !ok {
		t.Logf("No test data for method '%s' defined.\n", name)
		t.FailNow()
	}
	api := test.testFn(test.testData, &called)
	service := &TaskService{endpoint: api}
	serviceValue := reflect.ValueOf(service)
	testFn := serviceValue.MethodByName(name)
	if !testFn.IsValid() {
		t.Logf("Expected service to have method '%s', had not.\n", name)
		t.FailNow()
	}

	var args []reflect.Value
	for _, v := range test.args {
		args = append(args, reflect.ValueOf(v))
	}
	res := testFn.Call(args)

	if !called {
		t.Logf("Expected Api.%s method to have been called, was not.\n", name)
		t.Fail()
	}

	errors := test.testData.getErrors()

	if errors != "" {
		t.Logf("Found errors:\n%s", errors)
		t.Fail()
	}

	err := res[0]
	if err.IsNil() {
		t.Logf("Expected error not to be nil\n")
		t.Fail()
	}

	if !err.IsNil() {
		expectedMessage := "ERR"
		actualMessage := err.MethodByName("Error").Call([]reflect.Value{})[0].String()
		if expectedMessage != actualMessage {
			t.Logf("Expected error to have message '%q', got '%q'\n", expectedMessage, actualMessage)
			t.Fail()
		}
	}
}
