// DO NOT EDIT!
// This file is generated by the api generator.

// +build !feature

package harvest

import (
	"net/url"
)

type UserService struct {
	provider	CrudEndpointProvider
	endpoint	CrudTogglerEndpoint
}

func NewUserService(provider CrudEndpointProvider, endpoint CrudTogglerEndpoint) *UserService {
	service := UserService{
		provider:	provider,
		endpoint:	endpoint,
	}
	return &service
}

func (s *UserService) All(users *[]*User, params url.Values) error {
	return s.endpoint.All(users, params)
}

func (s *UserService) Find(id int, user *User, params url.Values) error {
	return s.endpoint.Find(id, user, params)
}

func (s *UserService) Create(user *User) error {
	return s.endpoint.Create(user)
}

func (s *UserService) Update(user *User) error {
	return s.endpoint.Update(user)
}

func (s *UserService) Delete(user *User) error {
	return s.endpoint.Delete(user)
}

func (s *UserService) Toggle(user *User) error {
	return s.endpoint.Toggle(user)
}
